### ISSUE TITLE
Replace local cache with the official coreDNS cache plugin

### ISSUE THREAD

**Issue by oz123** [oz123/coredns-netbox-plugin#1]

**Comment by andrewheberle** [comment]
Removing the local cache is reasonably simple and I'm happy to do a PR for this, but I'm not sure of the best option when parsing a `Corefile` that includes a `netbox` block with `localCacheDuration` set...

Do you think this should just be ignored with a warning logged? Or should this be a fatal error?

Breaking existing configs is always a bad thing...but also this is a pre-v1 release...so that might be ok.

What do you think @oz123?

**Comment by oz123** [comment]
Hi, I think a fatal error is OK, this has been on the road map for a very long time. Also, it is a very small user base that this change effects. It's pre-alpha software ...

**Comment by ahmedoun94** [comment]
I used the official cache plugin but metrics are not exported
