### ISSUE TITLE
CoreDNS server crashes

### ISSUE THREAD

**Issue by Peter2121** [oz123/coredns-netbox-plugin#7]
CoreDNS server with the plugin loaded crashes if the Netbox server is not available:
```
[FATAL] HTTP Error Get "http://10.111.1.130:8080/api/ipam/ip-addresses/?dns_name=aniva.reseaucloud.local": dial tcp 10.111.1.130:8080: connect: connection refused
consul.reseaucloud.local.:53
reseaucloud.local.:53
.:53
CoreDNS-1.8.0
freebsd/amd64, go1.15.6,
```

Zone `reseaucloud.local.` is configured to be resolved using Netbox plugin.

Please, fix the problem.

**Comment by oz123** [comment]
@Peter2121 I appreciate the continued feedback on this plugin. However, ATM I have higher priorities. If you need this ASAP please contact me on a private email.

**Comment by oz123** [comment]
@Peter2121 Thanks for pulling up your sleeves and contributing!

**Comment by 9600** [comment]
@oz123 looking at this and #8 from @Peter2121 I was wondering what the current status is? I'd love to use this plug-in, but CoreDNS crashing if Netbox is not available wouldn't be ideal.

**Comment by oz123** [comment]
Crashes only happen if something weird happens with deserialzation of data or if HTTP response parsing is not working.
This prevents error propagation upwards to responses.
It's my preference since I run the plugin in kubernetes. When it crashes, I see explicit restarts of the pod.
Having the plugin just log errors means that errors are silent and buried among other logs.
Other than that, the plugin is ok to use and does ok job.

**Comment by 9600** [comment]
@oz123 Many thanks for the clarification and, of course, writing the plug-in and making this available!

**Comment by oz123** [comment]
@andrewheberle CCing you here.
